apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
  namespace: fsprod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      labels:
        name: myapp
    spec:
      containers:
        - name: myapp
          image: nexusip/fsserver/imagename
          imagePullPolicy: Always
          volumeMounts:
            - name: fsapp-logs
              mountPath: /log
              subPath: myapp/log
              readOnly: false
            - name: fsserver
              mountPath: /config
              subPath: myapp/config
              readOnly: false
            - name: localtime
              mountPath: /etc/localtime
          ports:
            - containerPort: 10011
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:6.4.2
          args: [
              "-c", "/etc/filebeat.yml",
              "-e",
          ]
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: filebeat-config
              mountPath: /etc/filebeat.yml
              subPath: filebeat.yml
            - name: fsapp-logs
              mountPath: /log
      imagePullSecrets:
        - name: fsregsecret
      volumes:
        - name: fsserver
          persistentVolumeClaim:
            claimName: fsserver-home-pvc
        - name: localtime
          hostPath:
            # directory location on host
            path: /etc/localtime
        - name: fsapp-logs
          emptyDir: {}
        - name: filebeat-config
          configMap:
            name: filebeat-fsapp-config



